#!/usr/bin/env python3
"""Generate the iOS entry-type table from the backend's source catalog."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = Path(__file__).with_name("entry_type_catalog.json")
OUTPUT_PATH = ROOT / "ios" / "PlaceLogger" / "GeneratedEntryTypeCatalog.swift"
SWIFT_COLORS = {"pink", "orange", "purple", "green", "blue", "indigo", "teal", "mint", "red", "gray"}


def _swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render() -> str:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    rows: list[str] = []
    for entry in catalog:
        name = _swift_string(entry["name"])
        icon = entry["icon"]
        icon_expression = (
            f'.system({_swift_string(icon["system"])})'
            if "system" in icon
            else f'.asset({_swift_string(icon["asset"])})'
        )
        art = entry.get("art") or {}
        art_asset = (
            _swift_string(art["asset"])
            if art.get("asset")
            else "nil"
        )
        tint = art.get("tint", "gray")
        if tint not in SWIFT_COLORS:
            raise ValueError(f"Unsupported Swift color {tint!r} for {entry['name']}")
        rows.append(
            "    .init("
            f"type: {name}, icon: {icon_expression}, "
            f"artAssetName: {art_asset}, artTint: .{tint}"
            "),"
        )

    return "\n".join(
        [
            "// Generated by v0/generate_ios_entry_types.py from v0/entry_type_catalog.json.",
            "// Do not edit this file by hand.",
            "import SwiftUI",
            "",
            "extension SavedCategory {",
            "  static let known: [SavedCategory] = [",
            *rows,
            "  ]",
            "}",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit nonzero when the checked-in Swift table is stale.",
    )
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != generated:
            print(f"{OUTPUT_PATH} is not generated from {CATALOG_PATH}")
            return 1
        return 0
    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
