// Generated by v0/generate_ios_entry_types.py from v0/entry_type_catalog.json.
// Do not edit this file by hand.
import SwiftUI

extension SavedCategory {
  static let known: [SavedCategory] = [
    .init(type: "Restaurant", icon: .system("fork.knife"), artAssetName: "category-restaurant", artTint: .pink),
    .init(type: "Café", icon: .system("cup.and.saucer.fill"), artAssetName: "category-cafe", artTint: .orange),
    .init(type: "Cocktail Bar", icon: .asset("pin-martini-glass"), artAssetName: "category-bar", artTint: .purple),
    .init(type: "Club", icon: .system("hifispeaker.2.fill"), artAssetName: "category-bar", artTint: .purple),
    .init(type: "Wine Bar", icon: .asset("pin-wine-glass"), artAssetName: "category-bar", artTint: .purple),
    .init(type: "Pub", icon: .asset("pin-beer-mug"), artAssetName: "category-bar", artTint: .purple),
    .init(type: "Bakery", icon: .asset("pin-bread-slice"), artAssetName: "category-bakery", artTint: .orange),
    .init(type: "Museum", icon: .system("building.columns.fill"), artAssetName: "category-museum", artTint: .indigo),
    .init(type: "Art Gallery", icon: .asset("pin-curated-objects"), artAssetName: "category-art-gallery", artTint: .indigo),
    .init(type: "Furniture Store", icon: .asset("pin-couch"), artAssetName: "category-store", artTint: .teal),
    .init(type: "Clothes Store", icon: .system("tshirt.fill"), artAssetName: "category-store", artTint: .teal),
    .init(type: "Health and Beauty Store", icon: .asset("pin-pump-bottle"), artAssetName: "category-store", artTint: .teal),
    .init(type: "Misc. Store", icon: .system("bag.fill"), artAssetName: "category-store", artTint: .teal),
    .init(type: "Spa", icon: .system("bubbles.and.sparkles.fill"), artAssetName: "category-spa", artTint: .mint),
    .init(type: "Park", icon: .system("tree.fill"), artAssetName: "category-park", artTint: .green),
    .init(type: "Movie Theater", icon: .system("popcorn.fill"), artAssetName: "category-movie", artTint: .red),
    .init(type: "Bike Route", icon: .system("bicycle"), artAssetName: "category-bike-route", artTint: .blue),
    .init(type: "Hiking Trail", icon: .system("figure.hiking"), artAssetName: "category-hiking-trail", artTint: .green),
    .init(type: "Fitness", icon: .system("dumbbell.fill"), artAssetName: "category-fitness", artTint: .blue),
    .init(type: "Concert", icon: .asset("pin-guitar"), artAssetName: "category-concert", artTint: .purple),
    .init(type: "Pop-up", icon: .asset("pin-storefront"), artAssetName: "category-popup", artTint: .pink),
    .init(type: "Exhibit", icon: .asset("pin-images"), artAssetName: "category-exhibit", artTint: .indigo),
    .init(type: "Book", icon: .system("book.fill"), artAssetName: "category-book", artTint: .red),
    .init(type: "Movie", icon: .system("film.fill"), artAssetName: "category-movie", artTint: .red),
    .init(type: "Article", icon: .system("newspaper.fill"), artAssetName: "category-article", artTint: .red),
    .init(type: "Song", icon: .system("music.note"), artAssetName: "category-song", artTint: .purple),
    .init(type: "Product", icon: .system("shippingbox.fill"), artAssetName: "category-product", artTint: .teal),
    .init(type: "Unknown", icon: .system("questionmark.circle.fill"), artAssetName: "category-unknown", artTint: .gray),
  ]
}
